
package com.shtd.datasyncer.wsdl.qcjx;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DcmDataInfService", targetNamespace = "http://service.dcm.combanc.com/", wsdlLocation = "http://172.16.89.7:8080/DcmWs/DcmDataInfPort?wsdl")
public class DcmDataInfService
    extends Service
{

    private final static URL DCMDATAINFSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.shtd.datasyncer.wsdl.qcjx.DcmDataInfService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.shtd.datasyncer.wsdl.qcjx.DcmDataInfService.class.getResource(".");
            url = new URL(baseUrl, "http://172.16.89.7:8080/DcmWs/DcmDataInfPort?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.16.89.7:8080/DcmWs/DcmDataInfPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DCMDATAINFSERVICE_WSDL_LOCATION = url;
    }

    public DcmDataInfService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DcmDataInfService() {
        super(DCMDATAINFSERVICE_WSDL_LOCATION, new QName("http://service.dcm.combanc.com/", "DcmDataInfService"));
    }

    /**
     * 
     * @return
     *     returns DcmDataInfDelegate
     */
    @WebEndpoint(name = "DcmDataInfPort")
    public DcmDataInfDelegate getDcmDataInfPort() {
        return super.getPort(new QName("http://service.dcm.combanc.com/", "DcmDataInfPort"), DcmDataInfDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DcmDataInfDelegate
     */
    @WebEndpoint(name = "DcmDataInfPort")
    public DcmDataInfDelegate getDcmDataInfPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.dcm.combanc.com/", "DcmDataInfPort"), DcmDataInfDelegate.class, features);
    }

}
